# repository root netlify.toml
[build]
base = "/"
publish = "packages/playground-next/dist/public"
command = "pnpm --filter=@codeui/vanilla-extract build && pnpm --filter=@codeui/playground-next build"
