# repository root netlify.toml
[build]
base = "/"
publish = "packages/playground/dist/public"
command = "pnpm --filter=@codeimage/vanilla-extract build && pnpm --filter=@codeui/playground-next build"
