import { createThemeContract } from "@vanilla-extract/css";

export const tokens = createThemeContract({
	// ================================ tokens ================================ //
	background: null,
	foreground: null,
	accent1: null,
	accent2: null,
	accent3: null,
	accent4: null,
	accent5: null,
	accent6: null,
	accent7: null,
	accent8: null,
	accent9: null,
	accent10: null,
	brand: null,
	brandAccentHover: null,
	brandAccentActive: null,
	brandSoft: null,
	brandLink: null,
	brandSoftAccentHover: null,
	brandSoftAccentActive: null,
	critical: null,
	criticalAccentHover: null,
	criticalAccentActive: null,
	caution: null,
	cautionAccentHover: null,
	cautionAccentActive: null,
	neutral: null,
	neutralSoft: null,
	// ================================ forms ================================ //
	formAccent: null,
	// ================================ component ================================ //
	separator: null,
	dropdownBackground: null,
	dropdownBoxShadow: null,
	dropdownItemTextColor: null,
	dropdownItemHoverBackground: null,
	dropdownItemHoverTextColor: null,
} as const);
